=== jamieandrews/johar-git/resources/johar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- What goes inside a Parameter declaration -->
    <xs:complexType name="paramType">

	<xs:choice minOccurs="0" maxOccurs="unbounded">

	    <xs:element name="Type">
		<xs:simpleType>
		    <xs:restriction base="xs:string">
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="choice"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="file"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="int"/>
			<xs:enumeration value="text"/>
			<xs:enumeration value="tableEntry"/>
			<xs:enumeration value="timeOfDay"/>
		    </xs:restriction>
		</xs:simpleType>
	    </xs:element>

	    <xs:element name="Choices" minOccurs="0" maxOccurs="1"
			type="xs:string"/>
	    <xs:element name="DefaultValue" type="xs:string"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="DefaultValueMethod" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>

	    <xs:element name="FileConstraint" minOccurs="0" maxOccurs="1">
		<xs:simpleType>
		    <xs:restriction base="xs:string">
			<xs:enumeration value="mustExist"/>
    			<xs:enumeration value="mustBeReadable"/>
			<xs:enumeration value="mustNotExistYet"/>
		    </xs:restriction>
		</xs:simpleType>
	    </xs:element>

	    <xs:element name="RepsModel" minOccurs="0" maxOccurs="1">
		<xs:simpleType>
		    <xs:restriction base="xs:string">
			<xs:enumeration value="set"/>
    			<xs:enumeration value="multiset"/>
			<xs:enumeration value="sequence"/>
		    </xs:restriction>
		</xs:simpleType>
	    </xs:element>

	    <xs:element name="Label" minOccurs="0" maxOccurs="1"
			type="xs:string"/>
	    <xs:element name="MaxNumberOfChars" type="positiveInt"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="MaxNumberOfLines" type="positiveInt"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="MaxNumberOfReps" type="positiveInt"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="MinNumberOfReps" type="nonNegativeInt"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="MaxValue" type="xs:decimal"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="MinValue" type="xs:decimal"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Optional" type="joharBoolean"
			 minOccurs="0" maxOccurs="1"/>
	    <xs:element name="ParentParameter" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="ParentValue" minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Prominence" type="nonNegativeInt"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="SourceTable" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element ref="BriefHelp" minOccurs="0" maxOccurs="1"/>
	    <xs:element name="MultiLineHelp" type="xs:string"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element ref="OneLineHelp" minOccurs="0" maxOccurs="1"/>
	</xs:choice>

	<xs:attribute name="name" type="xs:string"/>
    </xs:complexType>


    <!-- What goes inside a Question declaration -->
    <xs:complexType name="questionType">
	<xs:complexContent>
	    <xs:extension base="paramType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
		    <xs:element name="AskIfMethod" type="lowerIdentifier"/>
		</xs:choice>
	    </xs:extension>
	</xs:complexContent>
    </xs:complexType>


    <!-- What goes inside a Stage declaration -->
    <xs:complexType name="StageContents">
	<xs:choice minOccurs="0" maxOccurs="unbounded">
	    <xs:element name="CommandMethod" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Label" type="xs:string"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Parameter" type="paramType"
			minOccurs="0" maxOccurs="unbounded"/>
	    <xs:element name="ParameterCheckMethod" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Question" type="questionType"
			minOccurs="0" maxOccurs="1"/>
	</xs:choice>
    </xs:complexType>


    <!-- One sequence of Stages -->
    <xs:group name="CommandStages">
	<xs:choice>
	    <xs:element name="Stage" type="StageContents"
			minOccurs="0" maxOccurs="unbounded"/>
	</xs:choice>
    </xs:group>


    <!-- Things that can go inside a Command declaration if there
	are no Stages -->
    <xs:group name="CommandContentsNoStages">
	<xs:choice>
	    <xs:element name="CommandMethod" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Parameter" type="paramType"
			minOccurs="0" maxOccurs="unbounded"/>
	    <xs:element name="ParameterCheckMethod" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Question" type="questionType"
			minOccurs="0" maxOccurs="1"/>
	</xs:choice>
    </xs:group>


    <!-- What goes inside a Command declaration -->
    <xs:complexType name="CommandType">
	<xs:choice minOccurs="0" maxOccurs="unbounded">
	    <xs:element name="ActiveIfMethod" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="Label" type="xs:string"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element ref="BriefHelp" minOccurs="0" maxOccurs="1"/>
	    <xs:element name="MultiLineHelp" type="xs:string"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element ref="OneLineHelp" minOccurs="0" maxOccurs="1"/>
	    <xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:group ref="CommandStages"/>
		<xs:group ref="CommandContentsNoStages"/>
	    </xs:choice>
	    <xs:element name="Prominence" type="nonNegativeInt"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="QuitAfter" type="joharBoolean"
			minOccurs="0" maxOccurs="1"/>
	    <xs:element name="QuitAfterIfMethod" type="lowerIdentifier"
			minOccurs="0" maxOccurs="1"/>
	</xs:choice>
    	<xs:attribute name="name" type="xs:string"/>
    </xs:complexType>


    <!-- The overall format of a Johar Interface Declaration File (IDF) -->
    <xs:element name="Johar">
	<xs:complexType>
	    <xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="Application" type="upperIdentifier"/>
		<xs:element name="ApplicationEngine" type="xs:string"
			    minOccurs="0" maxOccurs="1"/>
		<xs:element name="IdfVersion" type="xs:string"
			    maxOccurs="1"/>
		<xs:element ref="Table" minOccurs="0" maxOccurs="unbounded"/>
		<xs:element ref="CommandGroup"
			    minOccurs="0" maxOccurs="unbounded"/>
		<xs:element name="Command" type="CommandType"
			    maxOccurs="unbounded"/>
    	    </xs:choice>
	</xs:complexType>
    </xs:element>


    <!-- What goes inside a Table declaration -->
    <xs:element name="Table">
	<xs:complexType>
	    <xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="Browsable" type="joharBoolean"/>
		<xs:element name="DefaultHeading" type="xs:string"/>
	    </xs:choice>
	    <xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
    </xs:element>


    <!-- What goes inside a CommandGroup declaration -->
    <xs:element name="CommandGroup">
	<xs:complexType>
	    <xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="Member" type="xs:string"
			    minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="Mnemonic" type="xs:string"
			    minOccurs="0" maxOccurs="1"/>
	    </xs:choice>
	    <xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
    </xs:element>


    <xs:element name="BriefHelp" type="xs:string"/>


    <xs:element name="OneLineHelp" type="xs:string"/>


    <xs:simpleType name="joharBoolean">
	<xs:restriction base="xs:normalizedString">
	    <xs:enumeration value="yes"/>
    	    <xs:enumeration value="no"/>
    	    <xs:enumeration value="true"/>
    	    <xs:enumeration value="false"/>
	    <xs:enumeration value="Yes"/>
    	    <xs:enumeration value="No"/>
    	    <xs:enumeration value="True"/>
    	    <xs:enumeration value="False"/>
	    <xs:enumeration value="YES"/>
    	    <xs:enumeration value="NO"/>
    	    <xs:enumeration value="TRUE"/>
    	    <xs:enumeration value="FALSE"/>
      	</xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="positiveInt">
	<xs:restriction base="xs:integer">
    	    <xs:minInclusive value="1"/>
	</xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="nonNegativeInt">
	<xs:restriction base="xs:integer">
    	    <xs:minInclusive value="0"/>
	</xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="lowerIdentifier">
  	<xs:restriction base="xs:string">
	    <xs:pattern value="[\s]*[:]?[\s]*[a-z]([a-zA-Z0-9])*[\s]*"/>
 	</xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="upperIdentifier">
	<xs:restriction base="xs:string">
	    <xs:pattern value="[\s]*[A-Z]([a-zA-Z0-9])*[\s]*"/>
	</xs:restriction>
    </xs:simpleType>


</xs:schema>

=== jamieandrews/johar-git/src/johar/samples/IdesOfJohar.xml
<Johar
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="johar.xsd">

<Application>IdesOfJohar</Application>
<ApplicationEngine>IdesOfJohar</ApplicationEngine>
<IdfVersion>1.0</IdfVersion>
<Table name="weeks">
  <Browsable>yes</Browsable>
  <DefaultHeading>Weeks</DefaultHeading>
</Table>
<Table name="days">
  <Browsable>yes</Browsable>
  <DefaultHeading>Days</DefaultHeading>
</Table>
<Table name="appointments">
  <Browsable>yes</Browsable>
  <DefaultHeading>Appointments</DefaultHeading>
</Table>
<CommandGroup name="appointment">
  <Member>addAppointment</Member>
  <Member>cancel</Member>
  <Member>reminders</Member>
  <Member>exit</Member>
  <Mnemonic>M</Mnemonic>
</CommandGroup>
<CommandGroup name="previous">
  <Member>previousMonth</Member>
  <Member>previousWeek</Member>
  <Member>previousDay</Member>
  <Mnemonic>P</Mnemonic>
</CommandGroup>
<CommandGroup name="next">
  <Member>nextMonth</Member>
  <Member>nextWeek</Member>
  <Member>nextDay</Member>
  <Mnemonic>N</Mnemonic>
</CommandGroup>
<CommandGroup name="goTo">
  <Member>goToSelectedWeek</Member>
  <Member>goToSelectedDay</Member>
  <Member>goToDate</Member>
  <Mnemonic>G</Mnemonic>
</CommandGroup>
<Command name="addAppointment">
  <Label>Add Appointment</Label>
  <BriefHelp>Add an appointment</BriefHelp>
  <MultiLineHelp>Add an appointment on the current day</MultiLineHelp>
  <OneLineHelp>Add an appointment on the current day</OneLineHelp>
  <Parameter name="time">
    <Type>timeOfDay</Type>
    <DefaultValue>9:00 am</DefaultValue>
    <BriefHelp>Time of the appointment</BriefHelp>
    <MultiLineHelp>
            The time of the appointment. The format is hh:mm am.
    </MultiLineHelp>
    <OneLineHelp>Time of the appointment</OneLineHelp>
  </Parameter>
  <Parameter name="description">
    <Type>text</Type>
    <MaxNumberOfChars>240</MaxNumberOfChars>
    <MaxNumberOfLines>3</MaxNumberOfLines>
    <BriefHelp>Text description</BriefHelp>
    <MultiLineHelp>A description of the appointment in text format.</MultiLineHelp>
    <OneLineHelp>Text description of the appointment</OneLineHelp>
  </Parameter>
  <Parameter name="numReps">
    <Type>int</Type>
    <DefaultValue>1</DefaultValue>
    <Label>Number of repetitions</Label>
    <MinValue>1</MinValue>
    <BriefHelp>Number of repetitions</BriefHelp>
    <MultiLineHelp>
            The number of repetitions for the appointment, to be
            used with the &apos;Repeat Every&apos; parameter.  For example,
            2 daily repetitions will add the appointment twice, for two
            consecutive days.
    </MultiLineHelp>
    <OneLineHelp>Number of repetitions of the appointment</OneLineHelp>
  </Parameter>
  <Parameter name="repeatEvery">
    <Type>choice</Type>
    <Choices>day|week|month</Choices>
    <DefaultValue>day</DefaultValue>
    <BriefHelp>Repetition period</BriefHelp>
    <MultiLineHelp>
            The period of repetition of the appointment, which can be
            &apos;day&apos;, &apos;week&apos; or &apos;month&apos;.  For example, 3 repetitions with
            period &apos;day&apos; will add the appointment for 3 consecutive
            days; 3 repetitions with period &apos;week&apos; will add the
            appointment for 3 consecutive weeks on the same day of
            the week.
    </MultiLineHelp>
    <OneLineHelp>Period of repetition of the appointment</OneLineHelp>
  </Parameter>
</Command>
<Command name="cancel">
  <BriefHelp>Cancel appointment</BriefHelp>
  <MultiLineHelp>
    OneLineHelp   = &quot;Cancel the selected appointment&quot;
        Cancel the appointment that is selected from the appointment table.
  </MultiLineHelp>
  <Parameter name="appt">
    <Type>tableEntry</Type>
    <SourceTable>appointments</SourceTable>
    <BriefHelp>Selected appointment</BriefHelp>
    <MultiLineHelp>
            The selected row of the appointment table for cancellation.
    </MultiLineHelp>
    <OneLineHelp>The appointment to be cancelled</OneLineHelp>
  </Parameter>
</Command>
<Command name="reminders">
  <Parameter name="kind">
    <Type>choice</Type>
    <Choices>popup|email|off</Choices>
    <DefaultValue>off</DefaultValue>
    <Label>How do you want to be reminded?</Label>
    <BriefHelp>How you want to be reminded</BriefHelp>
    <MultiLineHelp>
            How you want to be reminded.  &apos;Popup&apos; means via a popup that
            appears on your screen.  &apos;Email&apos; means via email.  &apos;Off&apos;
            means that you do not want reminders.
    </MultiLineHelp>
    <OneLineHelp>How you want to be reminded</OneLineHelp>
  </Parameter>
</Command>
<Command name="previousMonth">
  <BriefHelp>Go to previous month</BriefHelp>
  <MultiLineHelp>Go to previous month</MultiLineHelp>
  <OneLineHelp>Go to previous month</OneLineHelp>
</Command>
<Command name="nextMonth">
  <BriefHelp>Go to next month</BriefHelp>
  <MultiLineHelp>Go to next month</MultiLineHelp>
  <OneLineHelp>Go to next month</OneLineHelp>
</Command>
<Command name="previousWeek">
  <BriefHelp>Go to previous week</BriefHelp>
  <MultiLineHelp>Go to previous week</MultiLineHelp>
  <OneLineHelp>Go to previous week</OneLineHelp>
</Command>
<Command name="nextWeek">
  <BriefHelp>Go to next week</BriefHelp>
  <MultiLineHelp>Go to next week</MultiLineHelp>
  <OneLineHelp>Go to next week</OneLineHelp>
</Command>
<Command name="previousDay">
  <BriefHelp>Go to previous day</BriefHelp>
  <MultiLineHelp>Go to previous day</MultiLineHelp>
  <OneLineHelp>Go to previous day</OneLineHelp>
</Command>
<Command name="nextDay">
  <BriefHelp>Go to next day</BriefHelp>
  <MultiLineHelp>Go to next day</MultiLineHelp>
  <OneLineHelp>Go to next day</OneLineHelp>
</Command>
<Command name="goToSelectedWeek">
  <BriefHelp>Go to selected week</BriefHelp>
  <MultiLineHelp>Go to the week selected from the Weeks table.</MultiLineHelp>
  <OneLineHelp>Go to the week selected from the Weeks table</OneLineHelp>
  <Parameter name="week">
    <Type>tableEntry</Type>
    <SourceTable>weeks</SourceTable>
    <BriefHelp>Selected week</BriefHelp>
    <MultiLineHelp>The week to go to, selected from the Weeks table.</MultiLineHelp>
    <OneLineHelp>The week to go to</OneLineHelp>
  </Parameter>
</Command>
<Command name="goToSelectedDay">
  <BriefHelp>Go to selected day</BriefHelp>
  <MultiLineHelp>Go to the day selected from the Days table.</MultiLineHelp>
  <OneLineHelp>Go to the day selected from the Days table</OneLineHelp>
  <Parameter name="day">
    <Type>tableEntry</Type>
    <SourceTable>days</SourceTable>
    <BriefHelp>Selected day</BriefHelp>
    <MultiLineHelp>The day to go to, selected from the Days table.</MultiLineHelp>
    <OneLineHelp>The day to go to</OneLineHelp>
  </Parameter>
</Command>
<Command name="goToDate">
  <BriefHelp>Go to specific date</BriefHelp>
  <MultiLineHelp>Jump to an arbitrary date.</MultiLineHelp>
  <OneLineHelp>Go to a specific date</OneLineHelp>
  <Parameter name="dateToGoTo">
    <Type>date</Type>
    <BriefHelp>Date to go to</BriefHelp>
    <MultiLineHelp>Date to go to.</MultiLineHelp>
    <OneLineHelp>Date to go to</OneLineHelp>
  </Parameter>
</Command>
<Command name="exit">
  <QuitAfter>yes</QuitAfter>
</Command>
</Johar>
